### ISSUE TITLE
Error on browser when execute npm start

### ISSUE THREAD

**Issue by ginatoriachambe** [khaledosman/react-redux-realworld-example-app#10]
Hello, I tried to run your project but I found error and I don't know how to solve.

The steps:
1 - I clone this repo
2- Run npm install
3-Run npm build
4- Open the browser

I found this error on the browser, Can you help me to solve this problem
![VirtualBox_Linux Ubuntu 3_11_04_2022_13_25_33](https://user-images.githubusercontent.com/44263333/162730276-78ecae0d-aab0-477d-bc97-5254c7e929ad.png)

**Comment by khaledosman** [comment]
sounds like the same issue with https://github.com/khaledosman/react-redux-realworld-example-app/issues/6 , This happens when the backend project is down/not running which is not handled by this repo, but another one... though we could probably have better error handling in place
